# Generated by Django 4.2 on 2023-12-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionreport',
            name='transaction',
        ),
    ]
